/*
 * Copyright (c) 2025, Team B
 * All rights reserved.
 */

#ifndef SOURCE_APP_PROJECTS_CONNECTIVITY_COMMON_RPMSG_COMM_H_
#define SOURCE_APP_PROJECTS_CONNECTIVITY_COMMON_RPMSG_COMM_H_

#endif  // SOURCE_APP_PROJECTS_CONNECTIVITY_COMMON_RPMSG_COMM_H_
