/*
 * Copyright (c) 2025, Team B
 * All rights reserved.
 */

#ifndef SOURCE_APP_PROJECTS_CONNECTIVITY_CA7_MQTT_MQTT_H_
#define SOURCE_APP_PROJECTS_CONNECTIVITY_CA7_MQTT_MQTT_H_

#endif  // SOURCE_APP_PROJECTS_CONNECTIVITY_CA7_MQTT_MQTT_H_
