name: Build Platform Firmware - Selective

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    # Job for connectivity project
    build-connectivity:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Check connectivity changes
          uses: dorny/paths-filter@v2
          id: connectivity-changes
          with:
            filters: |
              changed:
                - 'APP/projects/connectivity/**'
                - 'BSP/**'
                - 'UTIL_DRVR/**'
                - 'CMakeLists.txt'
                - 'Dockerfile'
        
        - name: Build connectivity firmware
          if: steps.connectivity-changes.outputs.changed == 'true'
          run: |
            docker build -t platform-builder .
            docker run --rm \
              -v $PWD/build-output-connectivity:/build-output \
              platform-builder \
              bash -c "
                mkdir build && cd build && 
                cmake .. -DCMAKE_TOOLCHAIN_FILE=../BSP/stm32/toolchain.cmake -DBUILD_CONNECTIVITY=ON && 
                make && 
                find . -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' | xargs -I {} cp {} /build-output/ 2>/dev/null || true
              "
        
        - name: Upload connectivity artifacts
          if: steps.connectivity-changes.outputs.changed == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: connectivity-firmware
            path: build-output-connectivity/*
            retention-days: 30

    # Job for controlBoard project
    build-controlboard:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Check controlBoard changes
          uses: dorny/paths-filter@v2
          id: controlboard-changes
          with:
            filters: |
              changed:
                - 'APP/projects/controlBoard/**'
                - 'BSP/**'
                - 'UTIL_DRVR/**'
                - 'CMakeLists.txt'
                - 'Dockerfile'
        
        - name: Build controlBoard firmware
          if: steps.controlboard-changes.outputs.changed == 'true'
          run: |
            docker build -t platform-builder .
            docker run --rm \
              -v $PWD/build-output-controlboard:/build-output \
              platform-builder \
              bash -c "
                mkdir build && cd build && 
                cmake .. -DCMAKE_TOOLCHAIN_FILE=../BSP/stm32/toolchain.cmake -DBUILD_CONTROLBOARD=ON && 
                make && 
                find . -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' | xargs -I {} cp {} /build-output/ 2>/dev/null || true
              "
        
        - name: Upload controlBoard artifacts
          if: steps.controlboard-changes.outputs.changed == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: controlBoard-firmware
            path: build-output-controlboard/*
            retention-days: 30

    # Job for oilMs project
    build-oilms:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Check oilMs changes
          uses: dorny/paths-filter@v2
          id: oilms-changes
          with:
            filters: |
              changed:
                - 'APP/projects/oilMs/**'
                - 'BSP/**'
                - 'UTIL_DRVR/**'
                - 'CMakeLists.txt'
                - 'Dockerfile'
        
        - name: Build oilMs firmware
          if: steps.oilms-changes.outputs.changed == 'true'
          run: |
            docker build -t platform-builder .
            docker run --rm \
              -v $PWD/build-output-oilms:/build-output \
              platform-builder \
              bash -c "
                mkdir build && cd build && 
                cmake .. -DCMAKE_TOOLCHAIN_FILE=../BSP/stm32/toolchain.cmake -DBUILD_OILMS=ON && 
                make && 
                find . -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' | xargs -I {} cp {} /build-output/ 2>/dev/null || true
              "
        
        - name: Upload oilMs artifacts
          if: steps.oilms-changes.outputs.changed == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: oilMs-firmware
            path: build-output-oilms/*
            retention-days: 30