name: Build Control Board Firmware

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-controlBoard-firmware:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker image
          run: |
            docker build -t platform-builder .

        - name: Build controlBoard firmware
          run: |
            docker run --rm \
              -v $PWD/build-output-controlBoard:/build-output \
               platform-builder \
               bash -c "
                 mkdir build && cd build && 
                 cmake .. -DCMAKE_TOOLCHAIN_FILE=../BSP/stm32/toolchain.cmake -DBUILD_CONTROLBOARD=ON && 
                 make && 
                 echo 'Copying controlBoard build artifacts...' && 
                 find . -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' | xargs -I {} cp {} /build-output/ 2>/dev/null || true
                "
        - name: Upload controlBoard artifacts
          uses: actions/upload-artifact@v4
          with:
            name: controlBoard-firmware
            path: build-output-controlBoard/*
            retention-days: 30
          