name: connectivity ci

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]
    workflow_dispatch:

jobs:

    # Build and test platform firmware
    build-and-test-firmware:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Initialize Submodules
          run: |
            git submodule update --init --recursive

        - name: Check for Source Code Changes
          uses: dorny/paths-filter@v2
          id: changes
          with:
            filters: |
              project:
                - 'source/**'
        
        - name: Build Docker Image
          run: |
            docker build -t platform-builder .

        - name: Build Firmware
          # if: steps.changes.outputs.project == 'true'
          run: |
            docker run --rm \
              -v $PWD:/workspace \
              platform-builder \
              bash -c "chmod +x scripts/run_build.sh && scripts/run_build.sh && \
              echo 'Copying connectivity build artifacts...' && \
              find . -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' | xargs -I {} cp {} /build-output/ 2>/dev/null || true"
        
        - name: Run MQTT Unit Tests with Valgrind
          run: |
            docker run --rm \
              -v $PWD:/workspace \
              platform-builder \
              bash -c "
              echo 'Building and running MQTT tests...' && \
              cd /workspace/tests/mqtt && \
              mkdir -p build && cd build && \
              cmake .. && \
              make && \
              echo '=== Running Tests Normally ===' && \
              ./mqtt_tests && \
              echo '=== Running Valgrind Memory Leak Check ===' && \
              valgrind --leak-check=full --show-leak-kinds=definite --quiet --error-exitcode=1 ./mqtt_tests 2>&1 | tee valgrind_report.txt && \
              echo '=== Valgrind Summary ===' && \
              grep -E '(LEAK SUMMARY|ERROR SUMMARY|definitely lost|All heap blocks)' valgrind_report.txt || echo 'No memory issues detected'"

        - name: Upload Test Reports
          uses: actions/upload-artifact@v4
          with:
            name: test-reports
            path: |
              tests/mqtt/build/valgrind_report.txt
            retention-days: 1
        
        - name: Run Cppcheck
          # if: steps.changes.outputs.project == 'true'
          run: |
            docker run --rm \
              -v $PWD:/workspace \
              platform-builder \
              bash -c "scripts/run_cppcheck.sh"

        - name: Run Cpplint
          run: |
            docker run --rm \
              -v $PWD:/workspace \
              platform-builder \
              bash -c "scripts/run_cpplint.sh"

        - name: Run Metrix++
          run: |
            docker run --rm \
              -v $PWD:/workspace \
              platform-builder \
              bash -c "scripts/run_metrix++.sh"
        
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: connectivity-firmware
            path: |
              build/images/*
              build/cppcheck/cppcheck_*.log
              build/cpplint/cpplint_*.log
              build/metrix++/metrix++_*.log
              tests/mqtt/build/valgrind_report.txt
            retention-days: 1
